FROM node:20-alpine

WORKDIR /app

ARG VITE_API_AUTH_BASE_URL
ARG VITE_API_POKEMON_BASE_URL

ENV VITE_API_AUTH_BASE_URL=$VITE_API_AUTH_BASE_URL
ENV VITE_API_POKEMON_BASE_URL=$VITE_API_POKEMON_BASE_URL

COPY package*.json ./
RUN npm ci

COPY . .

RUN npm run build

RUN npm install -g serve

EXPOSE 4173

CMD ["serve", "-s", "dist"]
